name: Build and Push SIF

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: openff-cu12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y apptainer

      - name: Verify installation
        run: apptainer --version

      - name: Build SIF image
        run: |
          apptainer build ${IMAGE_NAME}.sif openff-cu12.def

      - name: Test container
        run: |
          apptainer run --nv ${IMAGE_NAME}.sif

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
            | apptainer remote login \
                -u "${{ github.actor }}" \
                --password-stdin \
                oras://ghcr.io

      - name: Push image
        run: |
          TAG=${GITHUB_REF#refs/tags/}

          apptainer push \
            ${IMAGE_NAME}.sif \
            oras://ghcr.io/${{ github.repository }}/${IMAGE_NAME}:${TAG}

          apptainer push \
            ${IMAGE_NAME}.sif \
            oras://ghcr.io/${{ github.repository }}/${IMAGE_NAME}:latest
